ota_overlay:update ota-update
Signed-off-by: Chunrong Guo <chunrong.guo@nxp.com>

diff --git a/recipes-extended/ota_overlay/ota-overlay/merge/ota-update b/recipes-extended/ota_overlay/ota-overlay/merge/ota-update
--- a/recipes-extended/ota_overlay/ota-overlay/merge/ota-update
+++ b/recipes-extended/ota_overlay/ota-overlay/merge/ota-update
@@ -10,6 +10,7 @@ mid=`cat /tmp/ota-info | awk '{print $6}'`
 deviceid=`hostname`
 platform=$(echo $deviceid | awk -F . '{print $4}')
 boardname=$platform"rdb"
+bootimageVersion=`cat /etc/edgescale-version | awk -F '-' '{print $2}'`
 
 nofeedback=0
 
@@ -25,14 +26,14 @@ fi
 
 echo "updateStatus="$updateStatus
 echo "oldimageVersion="$oldimageVersion
-
+echo "bootimageVersion="$bootimageVersion
 get_imageURL(){
 	api_result=`curl "https://api.edgescale.org/v1/devices/softwares?device_id=$deviceid&solution=$solutionname&version=$imageVersion"`
 	imageURL=`echo $api_result | grep url | sed 's/\"//g' | sed 's/.*url:\(.*$\)/\1/' | awk -F "[,}]" '{print $1}' | sed 's/^[ \t]*//g'`
 }
 
 get_newimageVersion(){
-	api_result=`curl "https://api.edgescale.org/v1/devices/softwares?device_id=$deviceid"`
+	api_result=`curl "https://api.edgescale.org/v1/devices/softwares?device_id=$deviceid&version=$bootimageVersion"`
 	imageURL=`echo $api_result | grep url | sed 's/\"//g' | sed 's/.*url:\(.*$\)/\1/' | awk -F "[,}]" '{print $1}' | sed 's/^[ \t]*//g'`
 	newimageVersion=`echo $api_result | grep version | sed 's/\"//g' | sed 's/.*version:\(.*$\)/\1/' | awk -F "[,}]" '{print $1}' | sed 's/^[ \t]*//g'`
 	solutionname=`echo $api_result | grep solution | sed 's/\"//g' | sed 's/.*solution:\(.*$\)/\1/' | awk -F "[,}]" '{print $1}' | sed 's/^[ \t]*//g'`
@@ -90,6 +91,14 @@ security_check(){
 	fi
 }
 
+setup_ima_evm(){
+        if [ ! -f "/usr/bin/sec_imaevm" ]; then
+            echo "No found the integrity tool"
+        else
+            /usr/bin/sec_imaevm
+        fi
+}
+
 install_images(){
 	flex-installer -i pf -d sd
 	if [ ! -d "/run/media/mmcblk0p3" ];then
@@ -100,25 +109,37 @@ install_images(){
 	cd /run/media/mmcblk0p3/updateImages
 	wget -O full_images.tgz  $imageURL
 	tar -xf full_images.tgz
-	firmware_file=`ls *firmware*.img`
-	boot_file=`ls *boot*.tgz`
-	rootfs_file=`ls *rootfs*.tgz`
-	if [ ! -f "$firmware_file" ];then
-		echo "get firmware image error"
-		reboot
+	if [ ! -f "install.sh" ];then
+		firmware_file=`ls *firmware*.img`
+		boot_file=`ls *boot*.tgz`
+		rootfs_file=`ls *rootfs*.tgz`
+		if [ ! -f "$firmware_file" ];then
+			echo "get firmware image error"
+			reboot
+		fi
+		if [ ! -f "$boot_file" ];then
+			echo "get boot image error"
+			reboot
+		fi
+		if [ ! -f "$rootfs_file" ];then
+			echo "get rootfs image error"
+			reboot
+		fi
+		security_check
+		feedback_status "Deploying image into SD card"
+		flex-installer --firmware=$firmware_file --startblock=8 --device=/dev/mmcblk0
+		flex-installer -i install --bootpart=$boot_file --rootfs=$rootfs_file --machine=$boardname --device=sd
+               setup_ima_evm
+	else
+		chmod 777 ./install.sh
+		./install.sh
+		if [[ $? -eq 0 ]];then
+			echo "installer successed"
+		else
+			echo "installer failed"
+			reboot
+		fi
 	fi
-	if [ ! -f "$boot_file" ];then
-		echo "get boot image error"
-		reboot
-	fi
-	if [ ! -f "$rootfs_file" ];then
-		echo "get rootfs image error"
-		reboot
-	fi
-	security_check
-	feedback_status "Deploying image into SD card"
-	flex-installer --firmware=$firmware_file --startblock=8 --device=/dev/mmcblk0
-	flex-installer -i install --bootpart=$boot_file --rootfs=$rootfs_file --machine=$boardname --device=sd
 	rm -f /run/media/mmcblk0p3/updateImages/*
 	cd ~/
 	for i in {1..3}
